version = 0.1
[default.deploy.parameters]
stack_name = "sam-demo-sqs-lambda-s3"
resolve_s3 = true
s3_prefix = "sam-demo-sqs-lambda-s3"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
